services:
  Tab\Bundle\FrontendBundle\DataGrid\Extension\BrandIconExtension:
    arguments:
      - '@oro_attachment.manager'
      - '@oro_entity.doctrine_helper'
    tags:
      - oro_datagrid.extension
  Tab\Bundle\FrontendBundle\EventListener\ShoppingListDataGridListener:
    tags:
      - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.frontend-customer-user-shopping-list-grid, method: onBuildBefore }