datagrids:
  frontend-product-search-grid:
    options:
      jsmodules:
        - tabfrontend/js/app/datagrid/frontend-product-items-counter-builder

  frontend-customer-user-shopping-list-grid:
    options:
      toolbarOptions:
        pageSize:
          items: [0]
          default_per_page: 0
        pagination:
          onePage: true
      jsmodules:
        - tabfrontend/js/app/datagrid/shopping-list-sortable-builder
    source:
      query:
        select:
          - lineItem.checked
          - orderInfo.id as orderId
          - orderInfo.identifier
        join:
          left:
            - { join: lineItem.order, alias: orderInfo }
        orderBy:
          - column: lineItem.ordinal
            dir: ASC
          - column: lineItem.id
            dir: ASC
    columns:
      checked:
        frontend_type: shopping-list-item-checkbox
        editable: true
        order: 1
        label: ''
      orderInfo:
        frontend_type: html
        type: twig
        template: '@TabFrontend/Datagrid/ShoppingList/order.html.twig'
    properties:
      orderId: ~

  frontend-customer-user-shopping-list-edit-grid:
    inline_editing:
      plugin: tabfrontend/js/app/datagrid/plugins/shopping-list-inline-editing-plugin
