datagrids:
  frontend-product-search-grid:
    options:
      jsmodules:
        - tabfrontend/js/app/datagrid/frontend-product-items-counter-builder

  frontend-customer-user-shopping-list-grid:
    options:
      toolbarOptions:
        pagination:
          onePage: true
      jsmodules:
        - tabfrontend/js/app/datagrid/shopping-list-sortable-builder
    source:
      query:
        select:
          - lineItem.checked
          - orderInfo.id as orderId
        join:
          left:
            - { join: lineItem.order, alias: orderInfo }
        orderBy:
          - column: lineItem.ordinal
            dir: ASC
          - column: lineItem.id
            dir: ASC
    columns:
      checked:
        frontend_type: shopping-list-item-checkbox
        editable: true
        order: 1
        label: ''
    properties:
      orderId: ~
