imports:
  - { workflow: b2b_flow_checkout, as: practice_checkout, replace: [
    'transition_definitions.start_from_shoppinglist_definition.actions',
    'transition_definitions.finish_checkout_definition'
  ] }
  - { resource: 'practice_checkout/attributes.yml' }
  - { resource: 'practice_checkout/transition_definitions.yml' }
workflows:
  practice_checkout:
    entity: Oro\Bundle\CheckoutBundle\Entity\Checkout
    entity_attribute: checkout
    defaults:
      active: false
    priority: 200
